stages:
  - build
  - test
  - deploy staging
  - deploy production

include:
  - '.gitlab/common.yml'
  - '.gitlab/build.yml'
  - '.gitlab/test.yml'
  - '.gitlab/deploy-stag.yml'
  - '.gitlab/deploy-prod.yml'