stages:
  - build
  - deploy

.assume_role: &assume_role
  - >
    STS=($(aws sts assume-role-with-web-identity
    --role-arn ${ROLE_ARN}
    --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
    --web-identity-token $ID_TOKEN
    --duration-seconds 3600
    --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
    --output text))
  - export AWS_ACCESS_KEY_ID="${STS[0]}"
  - export AWS_SECRET_ACCESS_KEY="${STS[1]}"
  - export AWS_SESSION_TOKEN="${STS[2]}"

build:
    stage: build
    image: node:latest
    script:
        - npm install
        - npm run build
    artifacts:
        paths:
        - build/
    only:
      - main

deploy s3:
    stage: deploy
    image:
        name: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
        entrypoint:
          - '/usr/bin/env'
    id_tokens:
      ID_TOKEN:
        aud: our-identity-provider
    script:
        - *assume_role
        - aws s3 sync build/ s3://$S3_BUCKET_NAME --delete
    only:
      - main